image: rust:1.42

stages:
  - build
  - deploy

cache:
  paths:
    - cache

test_logic:
  stage: build
  before_script:
    - whereis cargo
    - rm -fr /usr/local/cargo/registry/index && mkdir -p cache/registry/index && ln -s cache/registry/index /usr/local/cargo/registry/index
    - rm -fr /usr/local/cargo/registry/cache && mkdir -p cache/registry/cache && ln -s cache/registry/cache /usr/local/cargo/registry/cache
    - rm -fr /usr/local/cargo/bin && mkdir -p cache/bin && ln -s cache/bin /usr/local/cargo/bin
    - rm -fr /usr/local/cargo/git/db && mkdir -p cache/git/db && ln -s cache/git/db /usr/local/cargo/git/db
    - rm -fr software/target && mkdir -p cache/$CI_COMMIT_REF_SLUG/target && ln -s cache/$CI_COMMIT_REF_SLUG/target software/target
    - source /usr/local/cargo/env
    - rustc --version
  script:
    - cd software/micromouse_logic
    - cargo test

build_firmware:
  stage: build
  before_script:
    - rm -fr /usr/local/cargo/registry/index && mkdir -p cache/registry/index && ln -s cache/registry/index /usr/local/cargo/registry/index
    - rm -fr /usr/local/cargo/registry/cache && mkdir -p cache/registry/cache && ln -s cache/registry/cache /usr/local/cargo/registry/cache
    - rm -fr /usr/local/cargo/bin && mkdir -p cache/bin && ln -s cache/bin /usr/local/cargo/bin
    - rm -fr /usr/local/cargo/git/db && mkdir -p cache/git/db && ln -s cache/git/db /usr/local/cargo/git/db
    - source /usr/local/cargo/env
    - rustc --version
  script:
    - rustup target add thumbv7em-none-eabihf
    - cd software/micromouse_firmware
    - cargo build --release
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-firmware"
    paths:
     - software/target/thumbv7em-none-eabihf/release/micromouse_firmware

build_simulation:
  stage: build
  before_script:
    - rm -fr /usr/local/cargo/registry/index && mkdir -p cache/registry/index && ln -s cache/registry/index /usr/local/cargo/registry/index
    - rm -fr /usr/local/cargo/registry/cache && mkdir -p cache/registry/cache && ln -s cache/registry/cache /usr/local/cargo/registry/cache
    - rm -fr /usr/local/cargo/bin && mkdir -p cache/bin && ln -s cache/bin /usr/local/cargo/bin
    - rm -fr /usr/local/cargo/git/db && mkdir -p cache/git/db && ln -s cache/git/db /usr/local/cargo/git/db
    - source /usr/local/cargo/env
    - rustc --version
  script:
    - cd software/micromouse_simulation
    - curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz > wasm-pack.tar.gz
    - tar -xvf wasm-pack.tar.gz
    - ./wasm-pack-v0.9.1-x86_64-unknown-linux-musl/wasm-pack build --out-dir static/pkg --target no-modules
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-simulation"
    paths:
      - software/micromouse_simulation/static

run_simulation:
  stage: deploy
  dependencies:
    - build_simulation
  before_script:
    - rm -fr /usr/local/cargo/registry/index && mkdir -p cache/registry/index && ln -s cache/registry/index /usr/local/cargo/registry/index
    - rm -fr /usr/local/cargo/registry/cache && mkdir -p cache/registry/cache && ln -s cache/registry/cache /usr/local/cargo/registry/cache
    - rm -fr /usr/local/cargo/bin && mkdir -p cache/bin && ln -s cache/bin /usr/local/cargo/bin
    - rm -fr /usr/local/cargo/git/db && mkdir -p cache/git/db && ln -s cache/git/db /usr/local/cargo/git/db
    - source /usr/local/cargo/env
    - rustc --version
  script:
    - cd software/micromouse_simulation
    - cargo run --bin run_sim > results
    - cat results | tail -n1 > metrics.txt
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-debug"
    paths:
      - software/micromouse_simulation/out.dat
      - software/micromouse_simulation/results
    reports:
      metrics: simulation/micromouse_simulation/metrics.txt

pages:
  stage: deploy
  dependencies:
    - build_simulation
  script:
    - cp -r software/micromouse_simulation/static public
  artifacts:
    paths:
      - public
  only:
    - master