image: rust:1.42

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - software/target

test_logic:
  stage: test
  script:
    - cd software/micromouse_logic
    - cargo test

build_firmware:
  stage: build
  script:
    - rustup target add thumbv7em-none-eabihf
    - cd software/micromouse_firmware
    - cargo build --release
  artifacts:
    paths:
     - software/target/thumbv7em-none-eabihf/release/micromouse_firmware

build_simulation:
  stage: build
  script:
    - cargo install wasm-pack
    - cd software/micromouse_simulation
    - sh ./build_wasm.sh
  artifacts:
    paths:
      - software/micromouse_simulation/static
