[package]
name = "simulation"
version = "0.1.0"
authors = ["Tim <timothyhollabaugh@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.105.0"
rand = "0.6.5"
mouse = { path = "../mouse" }
libm = "0.1"
serialport = "3.3"
plotters = "0.2"
image = "0.22"
conrod = { version = "0.61"}